config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  root "products#index"

  resources :finishs do
  collection do
    get 'search1'
      get 'search'
      get 'find'
      get 'find2'
      get 'find3'
      get 'find4'
      get 'find5'
      get 'find6'
      get 'find7'
      get 'find8'
      get 'index2'

end
end


  resources :pictures



 resources :products do
  
    
  collection do
    get 'search1'
      get 'search'
      get 'find'
      get 'find2'
      get 'find3'
      get 'find4'
      get 'find5'
      get 'find6'
      get 'find7'
      get 'find8'
end
end
end

app/models/finish.rb
class Finish < ActiveRecord::Base

  belongs_to :product
  has_many :pictures
 has_many :users

 validates_uniqueness_of :member_id


#必須項目
validates :member_id, presence: true, format: { with: /\A[!-~]+\z/i, :message => "「会員番号」は必須入力項目です。「会員番号」は半角で入力してください。 "}
validates :name, presence: {:message => "「名前」が入力されていません。「名前」は必須入力項目です"}
validates :first_day, presence: true, format: { with: /\A[!-~]+\z/i, :message => "「受注日」は必須入力項目です。「受注日」は半角で「2020/01/01」というように入力してください。"  }
validates :shop, presence: {:message => "「受注場所」が入力されていません。「受注場所」は必須入力項目です"}
validates :delivery_schedule, presence: true, format: { with: /\A[!-~]+\z/i, :message => "「納期」は半角で「2020/01/01」というように入力してください。「納期」は必須項目です。", allow_blank: true }


#数字のみ
validates :shitadori, numericality: { only_integer: true, :message => "「下取り」が間違っています。「下取り」数字のみ入力できます。" }
validates :price, numericality: { only_integer: true, :message => "「最終金額」が間違っています。「最終金額」数字のみ入力できます。" }
validates :uchikin, numericality: { only_integer: true, :message => "「内金」が間違っています。「内金」数字のみ入力できます。" }


#日付と半角
validates :sagyosyo_id, format: { with: /\A[!-~]+\z/i, :message => "「作業書番号」が間違っています。「作業書番号」は半角で入力してください。", allow_blank: true }
validates :syohin_id, format: { with: /\A[!-~]+\z/i, :message => "「商品番号」が間違っています。「商品番号」は半角で入力してください。", allow_blank: true }
validates :tel, format: { with: /\A[!-~]+\z/i, :message => "「電話番号」が間違っています。「電話番号」は半角で入力してください。", allow_blank: true }
validates :email, format: { with: /\A[!-~]+\z/i, :message => "が間違っています。「email」は半角で入力してください。", allow_blank: true }
validates :delivery_schedule, format: { with: /\A[!-~]+\z/i, :message => "「納期」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :delivery_string, format: { with: /\A[!-~]+\z/i, :message => "「納品日」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :sub_shop_delivery_string, format: { with: /\A[!-~]+\z/i, :message => "「本社→現場/品物到着日」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :main_shop_delivery_string, format: { with: /\A[!-~]+\z/i, :message => "「現場→本社/品物到着日」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :re_product_main_shop_delivery_string, format: { with: /\A[!-~]+\z/i, :message => "「再加工売場→本社/品物到着日」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :re_product_sub_shop_delivery_string, format: { with: /\A[!-~]+\z/i, :message => "「再加工本社→売場/品物到着日」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :matsuya_tsuuban, format: { with: /\A[!-~]+\z/i, :message => "「通番-※松屋のみ」は半角で入力してください。", allow_blank: true }
validates :product_first_day1, format: { with: /\A[!-~]+\z/i, :message => "「出し日1」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :product_delivery_schedule1, format: { with: /\A[!-~]+\z/i, :message => "「受取日1」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :product_delivery_day1, format: { with: /\A[!-~]+\z/i, :message => "「ライム納期1」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :product_first_day2, format: { with: /\A[!-~]+\z/i, :message => "「出し日2」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :product_delivery_schedule2, format: { with: /\A[!-~]+\z/i, :message => "「受取日2」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :product_delivery_day2, format: { with: /\A[!-~]+\z/i, :message => "「ライム納期2」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :product_first_day3, format: { with: /\A[!-~]+\z/i, :message => "「出し日3」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :product_delivery_schedule3, format: { with: /\A[!-~]+\z/i, :message => "「受取日3」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :product_delivery_day3, format: { with: /\A[!-~]+\z/i, :message => "「ライム納期3」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :product_first_day4, format: { with: /\A[!-~]+\z/i, :message => "「出し日4」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :product_delivery_schedule4, format: { with: /\A[!-~]+\z/i, :message => "「受取日4」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :product_delivery_day4, format: { with: /\A[!-~]+\z/i, :message => "「ライム納期4」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :pay_string, format: { with: /\A[!-~]+\z/i, :message => "「入金日」が間違っています。「入金日」は半角で「2020/01/01」というように入力してください。", allow_blank: true }
validates :uchikin_pay_string, format: { with: /\A[!-~]+\z/i, :message => "「内金入金日」が間違っています。「内金入金日」は半角で「2020/01/01」というように入力してください。", allow_blank: true }





  def price=(value)
    value.tr!('０-９', '0-9') if value.is_a?(String)
    super(value)
  end
  def shitadori=(value)
    value.tr!('０-９', '0-9') if value.is_a?(String)
    super(value)
  end
  def uchikin=(value)
    value.tr!('０-９', '0-9') if value.is_a?(String)
    super(value)
  end


def self.to_csv(options = {})#csvとエクセルで出力する処理(エンコーディング未処理)
    CSV.generate(options) do |csv|
      csv << csv_column_names
      all.each do |finish|
        csv << finish.csv_column_values
      end
    end
  end

def self.csv_column_names
    ["id", "会員番号", "作業書No ", "商品番号", "名前", "フリガナ", "電話番号", "E-mail", "郵便番号", "都道府県", "住所1", "住所2", "備考欄", "受注日/※必須入力", "受注場所", "納期/出来上り予定日/※必須入力", "納品日/お客様お渡し日", "本社→現場/品物到着日", " 現場→本社/品物到着日", "再加工売場→本社/品物到着日", " 再加工本社→売場/品物到着日", "通番-※松屋のみ", " 特記事項", " 加工出先1", "加工内容1", "出し日1", "ﾗｲﾑ納期1", "受取日1", " 加工出先2", "加工内容2", " 出し日2", " ﾗｲﾑ納期2", " 受取日2", "加工出先3", "加工内容3", " 出し日3", " ﾗｲﾑ納期3", "受取日3", "加工先4", "加工内容4", "出し日4", "ﾗｲﾑ納期4", "受取日4", "預かり品詳細", "受注商品名", " ﾃﾞｻﾞｲﾝNo．", "受注分類", "商品の種類", " 下取価格", "内金額", "差額-ご請求額", "備考", "入金日", "内金入金日", "担当者名", " お客様名", "お客様住所", "お客様ご連絡先", " お客様-ご来店の様子-※必須入力", "次回の期待が持てる方", "ｱﾝｹｰﾄ-ご来店のきっかけ", "ｱﾝｹｰﾄ-検索ｷｰﾜｰﾄﾞ", "ｱﾝｹｰﾄ-HP閲覧の時期-?日前", "ｱﾝｹｰﾄ-検索ｴﾝｼﾞﾝ", " ｱﾝｹｰﾄ-端末の種類", " ｱﾝｹｰﾄ-HPの印象", "ｱﾝｹｰﾄ-ｵｰﾀﾞｰｻﾝﾌﾟﾙ価格", "ｱﾝｹｰﾄ-ｵｰﾀﾞｰｻﾝﾌﾟﾙﾃﾞｻﾞｲﾝ", "ｱﾝｹｰﾄ-夢仕立を選んだ理由", "ｱﾝｹｰﾄ-HPの気になった所", " ｱﾝｹｰﾄ-今後欲しいｼﾞｭｴﾘｰ", " ｱﾝｹｰﾄ-掲載許可", "ｱﾝｹｰﾄ-ﾒｰﾙ連絡許可", "ｱﾝｹｰﾄ-ﾒｰﾙｱﾄﾞﾚｽ", " ｱﾝｹｰﾄ-性別", " ｱﾝｹｰﾄ-年代"]
  end

  def csv_column_values
    [id, member_id, sagyosyo_id, syohin_id, name, name_rubi, tel, email, post_no, prefectures, adress1, adress2, free_space1, first_day, shop, delivery_schedule, delivery_string, sub_shop_delivery_string, main_shop_delivery_string, re_product_main_shop_delivery_string, re_product_sub_shop_delivery_string, matsuya_tsuuban, special_topics, product_place1, product_reason1, product_first_day1, product_delivery_schedule1, product_delivery_day1, product_place2, product_reason2, product_first_day2, product_delivery_schedule2, product_delivery_day2, product_place3, product_reason3, product_first_day3, product_delivery_schedule3, product_delivery_day3, product_place4, product_reason4, product_first_day4, product_delivery_schedule4, product_delivery_day4, luggage_goods, product_name, design_no, product_category, product_kind, shitadori, uchikin, price, free_space2, pay_string, uchikin_pay_string, staff_id, customer_name, customer_adress, customer_telephone, customer_appearance, next_expected, visit_reason, search_keywords, show_string_hp, browser, terminal_kind, hp_impression, sample_price, sample_design, reason_of_yumejitate, bad_impression_hp, want_jewelry, publish_true, contact_true, customer_email, sex, age]


end
end

app/controllers/finishs_controller.rb
class FinishsController < ApplicationController

  before_action :authenticate_user!

  helper_method :sort_column, :sort_direction#並べ替えのヘルパーメソッドの定義


  def index
  @finishs = Finish.page(params[:page]).per(100).order(sort_column + " " + sort_direction)
  @pictures = @finishs.map(&:pictures).flatten

  respond_to do |format|#csvとエクセルで出力する処理(エンコーディング未処理)
      format.html
      format.csv { send_data @finishs.to_csv }
      format.xls { send_data @finishs.to_csv(col_sep: "\t")}
      end
 end

  def index2
    @finishs = Finish.all.order("first_day DESC")
    @pictures = @finishs.map(&:pictures).flatten

    respond_to do |format|#csvとエクセルで出力する処理(エンコーディング未処理)
      format.html
      format.csv { send_data @finishs.to_csv }
      format.xls { send_data @finishs.to_csv(col_sep: "\t")}
      end
  end

    def find
    @finish = Fnish.where(first_day: "#{params[:first_day_from]}".."#{params[:first_day_to]}")

  end
  def find2
@finish = Fnish.where(pay_string: "#{params[:pay_string_from]}".."#{params[:pay_string_to]}")
end
def find3
@finish = Fnish.where(delivery_string: "#{params[:delivery_string_from]}".."#{params[:delivery_string_to]}")


end
def find4
@finish = Fnish.where(delivery_schedule: "#{params[:delivery_schedule_from]}".."#{params[:delivery_schedule_to]}")

end
def find5
@finish = Fnish.where(product_delivery_schedule1: "#{params[:product_delivery_schedule1_from]}".."#{params[:product_delivery_schedule1_to]}")

end
def find6
@finish = Fnish.where(product_delivery_schedule2: "#{params[:product_delivery_schedule2_from]}".."#{params[:product_delivery_schedule2_to]}")
end
def find7
@finish = Fnish.where(product_delivery_schedule3: "#{params[:product_delivery_schedule3_from]}".."#{params[:product_delivery_schedule3_to]}")
end
def find8
@finish = Fnish.where(product_delivery_schedule4: "#{params[:product_delivery_schedule4_from]}".."#{params[:product_delivery_schedule4_to]}")
  end

  def search
  @finishs = Finish.where("concat(member_id, sagyosyo_id, syohin_id, shop, name, tel, email, prefectures, adress1, adress2, free_space1, first_day, delivery_schedule, delivery_string, sub_shop_delivery_string, main_shop_delivery_string, re_product_sub_shop_delivery_string, re_product_main_shop_delivery_string, matsuya_tsuuban, special_topics, product_place1, product_reason1, product_first_day1, product_delivery_schedule1, product_delivery_day1, product_place2, product_reason2, product_first_day2, product_delivery_schedule2, product_delivery_day2, product_place3, product_reason3, product_first_day3, product_delivery_schedule3, product_delivery_day3, product_place4, product_reason4, product_first_day4, product_delivery_schedule4, product_delivery_day4, luggage_goods, product_name, design_no, product_category, product_kind, price, free_space2, pay_string, uchikin_pay_string, staff_id, customer_name, customer_adress, customer_telephone, customer_appearance, visit_reason, search_keywords, show_string_hp, browser, terminal_kind, publish_true, contact_true, customer_email, sex, age) LIKE(?)", "%#{params[:keyword]}%").limit(100)

  end

  def search1
  @finishs = Finish.where("member_id LIKE(?)", "%#{params[:keyword]}%").limit(1000)
  
  end




def show
  @finish = Finish.find(params[:id])
  @pictures = @finish.pictures if @finish.pictures

end

def destroy
  finish = Finish.find(params[:id])
  #if tweet.user_id == current_user.id
   finish.destroy
  end


def edit
  @finish = Finish.find(params[:id])
  @pictures = @finish.pictures
  
end

def update
  @finish = Finish.find(params[:id])
  @picture = @finish
  @picture = Picture.create(pictures_params)
  @finish.update(finish_params_2)
  end


  private
  def finish_params
    params.require(:finish).permit(:member_id, :sagyosyo_id, :syohin_id, :shop, :name, :name_rubi, :tel, :email, :post_no, :prefectures, :adress1, :adress2, :free_space1, :first_day, :delivery_schedule, :delivery_string, :sub_shop_delivery_string, :main_shop_delivery_string, :re_product_sub_shop_delivery_string, :re_product_main_shop_delivery_string, :matsuya_tsuuban, :special_topics, :product_place1, :product_reason1, :product_first_day1, :product_delivery_schedule1, :product_delivery_day1, :product_place2, :product_reason2, :product_first_day2, :product_delivery_schedule2, :product_delivery_day2, :product_place3, :product_reason3, :product_first_day3, :product_delivery_schedule3, :product_delivery_day3, :product_place4, :product_reason4, :product_first_day4, :product_delivery_schedule4, :product_delivery_day4, :luggage_goods, :product_name, :design_no, :product_category, :product_kind, :shitadori, :uchikin, :price, :free_space2, :pay_string, :uchikin_pay_string, :staff_id, :customer_name, :customer_adress, :customer_telephone, :customer_appearance, :next_expected, :visit_reason, :search_keywords, :show_string_hp, :browser, :terminal_kind, :hp_impression, :sample_price, :sample_design, :reason_of_yumejitate, :bad_impression_hp, :want_jewelry, :publish_true, :contact_true, :customer_email, :sex, :age).merge(user_id: current_user.nickname)
  end

  def finish_params_2
    params.require(:finish).permit(:member_id, :sagyosyo_id, :syohin_id, :shop, :name, :name_rubi, :tel, :email, :post_no, :prefectures, :adress1, :adress2, :free_space1, :first_day, :delivery_schedule, :delivery_string, :sub_shop_delivery_string, :main_shop_delivery_string, :re_product_sub_shop_delivery_string, :re_product_main_shop_delivery_string, :matsuya_tsuuban, :special_topics, :product_place1, :product_reason1, :product_first_day1, :product_delivery_schedule1, :product_delivery_day1, :product_place2, :product_reason2, :product_first_day2, :product_delivery_schedule2, :product_delivery_day2, :product_place3, :product_reason3, :product_first_day3, :product_delivery_schedule3, :product_delivery_day3, :product_place4, :product_reason4, :product_first_day4, :product_delivery_schedule4, :product_delivery_day4, :luggage_goods, :product_name, :design_no, :product_category, :product_kind, :shitadori, :uchikin, :price, :free_space2, :pay_string, :uchikin_pay_string, :staff_id, :customer_name, :customer_adress, :customer_telephone, :customer_appearance, :next_expected, :visit_reason, :search_keywords, :show_string_hp, :browser, :terminal_kind, :hp_impression, :sample_price, :sample_design, :reason_of_yumejitate, :bad_impression_hp, :want_jewelry, :publish_true, :contact_true, :customer_email, :sex, :age).merge(edit_staff_id: current_user.nickname)

  end

  def pictures_params
    params.require(:finish).permit(:photo).merge(finish_id: @finish.id)
  end

 #並び替えの設定
  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
  end
 
  def sort_column
      Finish.column_names.include?(params[:sort]) ? params[:sort] : "first_day"
  end
end

app/helpers/finishs_helper.rb
module FinishsHelper
end

app/views/finishs/_finish_column_title.html.erb
<th>詳細</th>
<th><%= sortable "member_id", "会員番号" %></th>
<th><%= sortable "sagyosyo_id", "作業書番号" %></th>
<th><%= sortable "syohin_id", "商品番号" %></th>
<th><%= sortable "first_day", "受注日" %></th>
<th><%= sortable "delivery_schedule", "納期" %></th>
<th><%= sortable "delivery_string", "納品日" %></th>
<th><%= sortable "pay_string", "入金日" %></th>
<th><%= sortable "shop", "受注場所" %></th>
<th><%= sortable "name", "名前" %></th>
<th><%= sortable "name_rubi", "ふりがな" %></th>
<th><%= sortable "tel", "電話" %></th>
<th><%= sortable "email", "メール" %></th>
<th><%= sortable "post_no", "〒" %></th>
<th><%= sortable "prefectures", "都道府県" %></th>
<th><%= sortable "adress1", "住所1" %></th>
<th><%= sortable "adress2", "住所2" %></th>
<th><%= sortable "free_space1", "備考欄" %></th>
<th><%= sortable "sub_shop_delivery_string", "店舗→加工仕分け所" %></th>
<th><%= sortable "main_shop_delivery_string", "加工仕分け所→店舗" %></th>
<th><%= sortable "re_product_sub_shop_delivery_string", "店舗→加工仕分け所(再加工)" %></th>
<th><%= sortable "re_product_main_shop_delivery_string", "加工仕分け所→店舗(再加工)" %></th>
<th><%= sortable "matsuya_tsuuban", "松屋通番" %></th>
<th><%= sortable "special_topics", "特記事項" %></th>
<th><%= sortable "product_place1", "加工所1" %></th>
<th><%= sortable "product_reason1", "加工内容1" %></th>
<th><%= sortable "product_first_day1", "出し日1" %></th>
<th><%= sortable "product_delivery_schedule1", "ライム納期1" %></th>
<th><%= sortable "product_delivery_day1", "ライム到着日1" %></th>
<th><%= sortable "product_place2", "加工所2" %></th>
<th><%= sortable "product_reason2", "加工内容2" %></th>
<th><%= sortable "product_first_day2", "出し日2" %></th>
<th><%= sortable "product_delivery_schedule2", "ライム納期2" %></th>
<th><%= sortable "product_delivery_day2", "ライム到着日2" %></th>
<th><%= sortable "product_place3", "加工所3" %></th>
<th><%= sortable "product_reason3", "加工内容3" %></th>
<th><%= sortable "product_first_day3", "出し日3" %></th>
<th><%= sortable "product_delivery_schedule3", "ライム納期3" %></th>
<th><%= sortable "product_delivery_day3", "ライム到着日3" %></th>
<th><%= sortable "product_place4", "加工所4" %></th>
<th><%= sortable "product_reason4", "加工内容4" %></th>
<th><%= sortable "product_first_day4", "出し日4" %></th>
<th><%= sortable "product_delivery_schedule4", "ライム納期4" %></th>
<th><%= sortable "product_delivery_day4", "ライム到着日4" %></th>
<th><%= sortable "luggage_goods", "お預かり品" %></th>
<th><%= sortable "product_name", "受注商品名" %></th>
<th><%= sortable "design_no", "デザインナンバー" %></th>
<th><%= sortable "product_category", "受注分類" %></th>
<th><%= sortable "product_kind", "商品の種類" %></th>
<th><%= sortable "shitadori", "下取り金額" %></th>
<th><%= sortable "uchikin", "内金" %></th>
<th><%= sortable "price", "最終金額" %></th>
<th><%= sortable "free_space2", "備考欄2" %></th>
<th><%= sortable "uchikin_pay_string", "内金入金日" %></th>
<th><%= sortable "staff_id", "担当者名" %></th>
<th><%= sortable "customer_name", "お客様名" %></th>
<th><%= sortable "customer_adress", "お客様住所" %></th>
<th><%= sortable "customer_telephone", "お客様ご連絡先" %></th>
<th><%= sortable "next_expected", "次回の期待" %></th>
<th><%= sortable "visit_reason", "来店の理由" %></th>
<th><%= sortable "search_keywords", "検索キーワード" %></th>
<th><%= sortable "show_string_hp", "HPを見た日" %></th>
<th><%= sortable "browser", "ブラウザ" %></th>
<th><%= sortable "terminal_kind", "端末の種類" %></th>
<th><%= sortable "hp_impression", "HPの印象" %></th>
<th><%= sortable "sample_price", "サンプルの価格" %></th>
<th><%= sortable "sample_design", "サンプルのデザイン" %></th>
<th><%= sortable "reason_of_yumejitate", "夢仕立を選んだ理由" %></th>
<th><%= sortable "bad_impression_hp", "HPの気になった点" %></th>
<th><%= sortable "want_jewelry", "今後欲しいジュエリー" %></th>
<th><%= sortable "publish_true", "掲載可" %></th>
<th><%= sortable "contact_true", "メール可" %></th>
<th><%= sortable "customer_email", "お客様のメールアドレス" %></th>
<th><%= sortable "sex", "性別" %></th>
<th><%= sortable "age", "年代" %></th>
<th><%= sortable "user_id", "登録者" %></th>
<th><%= sortable "edit_staff_id", "最終編集者" %></th>
 <th>画像_1</th>
      <th>画像1名</th>
      <th>画像1記録日時</th>
      <th>画像_2</th>
      <th>画像2名</th>
      <th>画像2記録日時</th>
      <th>画像_3</th>
      <th>画像3名</th>
      <th>画像3記録日時</th>
      <th>画像_4</th>
      <th>画像4名</th>
      <th>画像4記録日時</th>
      <th>画像_5</th>
      <th>画像5名</th>
      <th>画像5記録日時</th>

app/views/finishs/_finish_find_form.html.erb
<div class="product_find_form">
<p>
  ダウンロード(Libre Office以外では文字化けします!エンコード:UTF-8):<br><!--csvとエクセルで出力する処理(エンコーディング未処理)-->
  <%= link_to "CSV", index2_finishs_path(format: "csv") %>
  |
  <%= link_to "Excel", index2_finishs_path(format: "xls") %>
</p>
<p>※検索ボタンを押しても反応がない場合は、一度ページを更新してください</p>
<%= form_tag("/finishs/search1", method: :get) do %>
                <input class="search__query" name="keyword" placeholder="会員番号検索" type="text" value=""><input type="submit" value="会員番号検索">
                <% end %>

     <%= form_tag("/finishs/search", method: :get) do %>
                <input class="search__query" name="keyword" placeholder="フリーワード検索" type="text" value=""><input type="submit" value="フリーワード検索">
                <% end %>

  <%= form_tag("/products/find", method: :get) do %>
                <p>
                受注日検索　　　　　　　　　：
                <input placeholder="0000/00/00と入力" type="text" name="first_day_from">〜
                <input placeholder="0000/00/00と入力" type="text" name="first_day_to">
                <input type="submit" value="受注日検索">
              </p>
              <% end %>
              <%= form_tag("/products/find2", method: :get) do %>
              <p>
                入金日検索　　　　　　　　　：
      <input placeholder="0000/00/00と入力" type="text" name="pay_string_from">〜
      <input placeholder="0000/00/00と入力" type="text" name="pay_string_to">
           <input type="submit" value="入金日検索">
    </p>
    <% end %>
    <%= form_tag("/products/find3", method: :get) do %>
    <p>

                納品日検索　　　　　　　　　：
      <input placeholder="0000/00/00と入力" type="text" name="delivery_string_from">〜
      <input placeholder="0000/00/00と入力" type="text" name="delivery_string_to">
           <input type="submit" value="納品日検索">
    </p>
    <% end %>
    <%= form_tag("/products/find4", method: :get) do %>
    <p>
    
                納品予定日検索　　　　　　　：
                <input placeholder="0000/00/00と入力" type="text" name="delivery_schedule_from">〜
                <input placeholder="0000/00/00と入力" type="text" name="delivery_schedule_to">
                     <input type="submit" value="納期検索">
              </p>
              <% end %>
              <%= form_tag("/products/find5", method: :get) do %>
              <p>
                加工先1ライム到着予定日検索：
     <input placeholder="0000/00/00と入力" type="text" name="product_delivery_schedule1_from">〜
     <input placeholder="0000/00/00と入力" type="text" name="product_delivery_schedule1_to">
          <input type="submit" value="加工1検索">
     </p>
     <% end %>
     <%= form_tag("/products/find6", method: :get) do %>
     <p>
                加工先2ライム到着予定日検索：
     <input placeholder="0000/00/00と入力" type="text" name="product_delivery_schedule2_from">〜
     <input placeholder="0000/00/00と入力" type="text" name="product_delivery_schedule2_to">
          <input type="submit" value="加工2検索">
          </p>
          <% end %>
          <%= form_tag("/products/find7", method: :get) do %>
     <p>
                加工先3ライム到着予定日検索：
     <input placeholder="0000/00/00と入力" type="text" name="product_delivery_schedule3_from">〜
     <input placeholder="0000/00/00と入力" type="text" name="product_delivery_schedule3_to">
          <input type="submit" value="加工3検索">
          </p>
          <% end %>
          <%= form_tag("/products/find8", method: :get) do %>
     <p>
                加工先4ライム到着予定日検索：
     <input placeholder="0000/00/00と入力" type="text" name="product_delivery_schedule4_from">〜
     <input placeholder="0000/00/00と入力" type="text" name="product_delivery_schedule4_to">
          <input type="submit" value="加工4検索">
     </p>
<% end %>


                 <div class="link_to_page"><p><%= link_to "現行一覧", products_path %></p></div>
                 <div class="link_to_page"><p><%= link_to "過去一覧", finishs_path %></p></div>
              <div class="link_to_page"><p><%= link_to "新規登録", new_product_path %></p></div>
              <div class="link_to_page"><p><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></p></div>

 
    </div>
              

app/views/finishs/_title_form.html.erb
<div class="title_font">
夢仕立<font style="color: blue;">＜納品済み＞</font>一覧
  </div>

app/views/finishs/create.html.erb
<div>
    <div>
      <h3>
        納品後登録を終了しました。<br>
        ※納品後登録の確認後、現行一覧から該当のデータを削除してください。
      </h3>
      <a href="/">一覧へ戻る</a>
    </div>
  </div>

app/views/finishs/find2.html.erb
<html>

<p><%= render partial: "title_form" %></p>

<table class="table_design">
<tr>
<%= render partial: "finish_column_title" %>
    </tr>

    <% a_price = 0 %>
<% @finishs.each do |finish| %>
 <tr>
 <td><%= render partial: "finish", locals: {finish: finish} %></td>
<%= render partial: "finish_list", locals: {finish: finish} %>

    </tr>
    <% a_price = a_price + finish.price if finish.price %>
    <% end %>

                <div style="foat: left;">
                <%= render partial: "finish_find_form" %>
              </div>



              <div>
              <% if current_user.id == (1 || 2 || 3) %>
              <div>合計:<%= number_to_currency(a_price,:precision =>0, :format=>"%n%u", :unit=>"円") %></div><!--precisionは小数点。標準だと小数点以下2位まで表示。%nはナンバー、%uがユニット。-->
                <% end %>
              </div>
</table>
  </html>